name: Run UI Test with Suites

on: workflow_dispatch

jobs:
  CheckoutAndBuild:
    name: "Checkout source code and Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.PAT_GITHUB }}
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: Erase all simulator
        run: xcrun simctl erase all
      - name: Killing all active simulator===
        run: killall "Simulator" || true
      - name: Setup Pod
        if: success() || failure()
        working-directory: ./iOSUITests
        run: pod install
      - name: Safari UI tests
        if: success() || failure()
        working-directory: ./iOSUITests
        run: xcodebuild test -workspace UITestPOC.xcworkspace -scheme UITestPOCUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -only-testing UITestPOCUITests/SafariAppTests -verbose
      - name: PasteBoard UI tests
        if: success() || failure()
        working-directory: ./iOSUITests
        run: xcodebuild test -workspace UITestPOC.xcworkspace -scheme UITestPOCUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -only-testing UITestPOCUITests/UIPasteBoardTests -verbose
      - name: UIlayouts UI Tests
        if: success() || failure()
        working-directory: ./iOSUITests
        run: xcodebuild test -workspace UITestPOC.xcworkspace -scheme UITestPOCUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -only-testing UITestPOCUITests/UILayoutViewsTests
      - name: Product UI tests
        if: success() || failure()
        working-directory: ./iOSUITests
        run: xcodebuild clean test -workspace UITestPOC.xcworkspace -scheme UITestPOCUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -only-testing UITestPOCUITests/ProductListUITests
      - name: Login UI tests
        if: success() || failure()
        working-directory: ./iOSUITests
        run: xcodebuild test -workspace UITestPOC.xcworkspace -scheme UITestPOCUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -only-testing UITestPOCUITests/LoginUITests
      - name: ActionSheet UI tests
        if: success() || failure()
        working-directory: ./iOSUITests
        run: xcodebuild test -workspace UITestPOC.xcworkspace -scheme UITestPOCUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -only-testing UITestPOCUITests/ActionSheetTests
      - name: Activity UI tests
        if: success() || failure()
        working-directory: ./iOSUITests
        run: xcodebuild test -workspace UITestPOC.xcworkspace -scheme UITestPOCUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -only-testing UITestPOCUITests/ActivityControllerTests
