name: Run UI Regression tests

on: workflow_call:

jobs:
  CheckoutAndBuild:
    name: "Checkout source code and Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{secrets.PAT_GITHUB }}


        
