
 source 'https://github.com/awasthi027/ios-spec.git'

 platform :ios, '16.0'

target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!
   pod 'api-ios'

  # Pods for TestApp

  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'api-ios'
  end

  target 'TestAppUITests' do
    # Pods for testing
    pod 'api-ios'
  end

end
