# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'API-iOS'
  # Pods for TestApp

  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
#    pod 'API-iOS'
  end

  target 'TestAppUITests' do
    # Pods for testing
#    pod 'API-iOS'
  end

end
