# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
podspec_name = "API-iOS.podspec" # Don’t forget to update the podspec_name to the name of your podspec file.
platform :ios do
  desc "Releases a new version automatically"
   lane :release do
     pod_lib_lint
   end
end
