name: Shared CI Workflow for Pull Request

on:
  workflow_call:
    inputs:
      config_path:
        description: 'Path for json config file'
        required: true
        type: string
      quality-check-config-path:
        description: 'Path for json quality check config file'
        required: false
        type: string
        default: ''
      config_schema_paths:
        description: 'Paths for json config schema'
        required: false
        type: string
        default: |
          ./template/schema/schema-basic.json
          ./template/schema/schema-ci.json
      repository:
        description: 'The owner and repository name.'
        required: false
        type: string
        default: ${{ github.repository }}
      ref:
        description: 'The fully-formed ref of the branch or tag that triggered the workflow run'
        required: false
        type: string
        default: ${{ github.ref }}
      runtime-overrides:
        description: '[Deprecated] Custom runtime overrides'
        required: false
        type: string
        default: ''
      input-params:
        description: 'Input parameters for custom runtime overrides from the caller'
        required: false
        type: string
        default: ''
    outputs:
      config:
        description: 'Music Sheet Configuration'
        value: ${{ inputs.config }}

permissions:
  contents: read

jobs:
  prepare:
     name: '🌱 Seed Workflow Config 🌱'
     runs-on: [macos-latest]
     outputs:
      matrix: ${{ steps.readjson.outputs.config-content }}
     steps:

      - name: Checkout Project Repository
        uses: actions/checkout@main
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.PAT_GITHUB }}

      - name: Validate Build Configuration
        id: readjson
        uses: awasthi027/validate-workflow-config-action@v1
        with: 
          config-path: ${{ inputs.config_path }}
          schema-paths: ${{ inputs.config_schema_paths }}

  call-prebuild:
    name: 'Prebuild'
    needs: prepare
    uses: awasthi027/shared-stages/.github/workflows/main-prebuild.yml@main
    with:
      config: ${{ needs.prepare.outputs.matrix }}
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
    secrets: inherit

  # call-build:
  #   name: 'Build'
  #   needs: call-prebuild
  #   uses: euc-uem/shared-stages/.github/workflows/main-build.yml@dev
  #   with:
  #     config: ${{ needs.call-prebuild.outputs.config }}
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #   secrets: inherit

  # call-test:
  #   name: 'Test'
  #   needs: call-build
  #   uses: euc-uem/shared-stages/.github/workflows/main-test.yml@dev
  #   with:
  #     config: ${{ needs.call-build.outputs.config }}
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #   secrets: inherit

  # call-postbuild:
  #   name: 'Postbuild'
  #   needs: call-test
  #   uses: euc-uem/shared-stages/.github/workflows/main-postbuild.yml@dev
  #   with:
  #     config: ${{ needs.call-test.outputs.config }}
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #   secrets: inherit
