name: CI

on: workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.PAT_GITHUB }}
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          bundle install
          git config user.email "myemail.awasthi@gmail.com"
          git config user.name "Github Actions Bot"
          fastlane publicNewPod
