name: CI

on: workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          bundle install
          git config --global user.name 'Ashish Awasthi'
          git config --global user.email 'awasthi027@users.noreply.github.com'
          fastlane publicNewPod
