name: CI

on: workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          fastlane publicNewPod
